#1 = 1min 1,2 = 1min - 2min
PickTime: "1,3"

#Cannt pick servers.
BlockedServerName:
  - "Server1"
  - "Server2"

#Pick Mode 1 / 2
Mode: 1

#Mode1
Pick1Level:
  - "1,1ren"
  - "10,10ren"
  - "20,20ren"
  - "30,30ren"

#Mode2
# 20%
Pick2Pitch: 20
#Min 2 players
Min: 2